# Generated by Django 4.0 on 2022-01-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0002_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.BinaryField(null=True),
        ),
    ]
