# Generated by Django 4.0 on 2022-01-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0003_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
