# Generated by Django 4.0 on 2022-01-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0005_remove_note_file_notefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.DeleteModel(
            name='NoteFile',
        ),
    ]
