# Generated by Django 4.0 on 2022-01-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0006_note_file_delete_notefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
