# Generated by Django 4.0 on 2022-02-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0008_alter_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tag',
            field=models.ManyToManyField(to='evernote.Tag'),
        ),
        migrations.DeleteModel(
            name='NoteHasTag',
        ),
    ]
