# Generated by Django 4.0 on 2022-02-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0009_note_tag_delete_notehastag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tag',
            new_name='tags',
        ),
    ]
