# Generated by Django 4.0 on 2022-03-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evernote', '0011_alter_note_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='evernote.Tag'),
        ),
    ]
